server:
  port: 8081  # 服务器端口设置为 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fiveshop?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root  # 数据库用户名
    password: 55555  # 数据库密码
    driver-class-name: com.mysql.cj.jdbc.Driver  # MySQL 驱动类名
  web:
    resources:
      static-locations: file:/C:/Users/asus/Desktop/javaweb/fiveshop/uploads/  # 静态资源文件夹路径

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true  # 映射下划线为驼峰命名
  mapper-locations: classpath:/mapper/*Mapper.xml  # Mapper XML 文件的路径
  type-aliases-package: com.fiveshop.fiveshop.entity  # 实体类的包路径

logging:
  level:
    root: INFO  # 日志级别设置为 INFO
