server:
    port: 8081


# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fiveadmin?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 55555
  output:
    ansi:
      enabled: always
  # security:
  #   user:
  #     name: user
  #     password: 55555

  data:  # 將 Redis 配置放入 data 下
    redis:
      host: 127.0.0.1
      port: 6379
      password: 55555

mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml

